# This workflow will upload a Python Package using uv when a release is created
# For more information see: https://docs.github.com/en/actions/how-tos/use-cases-and-examples/building-and-testing/building-and-testing-python#publishing-to-pypi

name: Nightly Upload to Test PyPI

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs: {}

jobs:
  build:
    name: Build Mitiq
    if: github.repository_owner == 'unitaryfoundation'
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/mitiq/
    permissions:
      id-token: write
    steps:
      - name: Check out mitiq
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"

      - name: change mitiq version
        run: |
          truncate -s -1 VERSION.txt
          echo "$(date +"%Y%m%d")" >> VERSION.txt

      - name: Build mitiq
        run: uv build

      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
