# This workflow will upload a Python Package using uv when a release is created
# For more information see: https://docs.github.com/en/actions/how-tos/use-cases-and-examples/building-and-testing/building-and-testing-python#publishing-to-pypi

name: Upload Release Package to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs: {}

jobs:
  deploy:
    if: github.repository_owner == 'unitaryfoundation'
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write

    steps:
      - name: Check out mitiq
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.12"

      - name: Build package
        run: uv build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
